### ISSUE TITLE
Change command names

### ISSUE THREAD

**Issue by cclamb** [DerekSelander/LLDB#10]
Would you be opposed to changing some of the command names? I have some name collisions I'd like to avoid. I can make the change and submit a pull request if you're cool with it.

**Comment by DerekSelander** [comment]
Reluctant to change the names around since they are tied to lessons in the debugging book but I’ll consider making a renaming functionality so you can override the command names

**Comment by simsong** [comment]
You can create new names and have the old names be aliases for the new names!

**Comment by DerekSelander** [comment]
You know what, @simsong is right, @cclamb, you can put my script importer at the start of your `~/.lldbinit` file.  Redeclare my commands to your new desired names, and then declare your custom commands after mine.  

So let's say you wanted to change my `search` command to `yay_search`, My `~/.lldbinit` would look like the following: 

```
command script import /Users/derekselander/lldb_repo/lldb_commands/dslldb.py
command script add -f search.search yay_search

# your custom commands heres
```
