### ISSUE TITLE
Enumerating NoneType

### ISSUE THREAD

**Issue by cclamb** [DerekSelander/LLDB#11]
So there's a bug that seems pretty endemic with respect to enumerating a NoneType. You can see it in search at line 110 (I think i may be a python3 issue?):

Currently in search.py:110: if 'nil' in res.GetOutput():

Fixed with?
ro = res.GetOutput()
if ro is None or 'nil' in res.GetOutput():

Not sure if this is correct though.

**Comment by jasonmolenda** [comment]
You could try calling res.HasResult() before grabbing the output.  If SBCommandReturnObject::GetOutput() is returning None, my guess is that the expression (HandleCommand() call) couldn't be executed for some reason.  There's also a SBCommandReturnObject::Succeeded() method.

**Comment by cclamb** [comment]
That sounds like a better solution (e.g. ::HasOuput()). I'll look at making
these changes and submitting a pull request. ::Succeeded() should likely be
used as well, I'll see where it makes sense.
