### ISSUE TITLE
Any way to implement mshookfunction use lldb python api or dynamic load a dylib?

### ISSUE THREAD

**Issue by CodeLife2012** [DerekSelander/LLDB#17]
This project implement many awesome commands to inspect the process, I just curious how to alter the program execution. Breakpoint with expression seems can do this, but seems not a effective way, do you have any suggestions?

**Comment by DerekSelander** [comment]
I wouldn't recommend LLDB to be the primary tool to interpose code.  

LLDB has simple program control over program execution.  See `help thread`. I'd recommend using other tools to interpose code and possibly use LLDB to load it.
