### ISSUE TITLE
Chapter 1: No LLDB prompt after Xcode launch 

### ISSUE THREAD

**Issue by rssole** [DerekSelander/LLDB#37]
Hi, perhaps I am missing something but following the book Ch 1, 
after launching Xcode there is no longer lldb prompt which would allow
entering subsequent commands. It just prints out Xcode has been launched 
and never getting back to prompt: (lldb). Where I might be wrong?

Scanning over lldb docs didn't yield too much.

**Comment by kasimok** [comment]
In your LLDB tab, type Ctrl + C to pause the debugger.
