### ISSUE TITLE
error: use of undeclared identifier

### ISSUE THREAD

**Issue by gaplan** [DerekSelander/LLDB#7]
(lldb) overlaydbg
error: use of undeclared identifier 'UIDebuggingInformationOverlay'

IOS 11.4.1
i don't understand this error ?

**Comment by crsantos** [comment]
It works ok here... 🤔 

```bash
(lldb) overlaydbg
Displaying UIDebuggingInformationOverlay... resume execution
```

Have you followed the [Installation](https://github.com/DerekSelander/LLDB#installation)?

**Comment by DerekSelander** [comment]
@gaplan  `UIDebuggingInformationOverlay` is an Objective-C class that is private to Apple that helps in debugging. Can you try a `po [UIDebuggingInformationOverlay class]` to see if anything pops up. If yes, it's something with the script, if no, you it's something on your end.

**Comment by DerekSelander** [comment]
Closing for now, please reopen if you can still reproduce
